books/urls.py
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'books'

urlpatterns = [


	path('books-by-genres/',views.return_books_by_ganres,name='books_by_ganres'),
	path('comment-rating-system/',views.comment_like_dislike_system,name='comment_system'),
	path('book-rating-system/',views.book_like_dislike_system,name='system'),
	path('books-you-have-searched-for/',views.search_book,name='search'),
	path('delete-comment/<int:comm_id>/<int:book_id>/',views.delete_comment,name='comm_delete'),
	path('star/<int:book_id>/',views.rating_star_system,name='rating_star'),
	path('un-rate/<str:slug>/<int:user_id>/',views.delete_user_stars,name='user_stars_delete'),
	path('book-by-genre/<str:gen>/',views.get_one_genre_books ,name='one_genre'),

	path('page-num-update-comm/<slug:slug>/<page_num_update_comment>/',views.book, name='book-comment'),
	path('book/<slug:slug>/',views.book, name='book'),

]

forum4/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .import views



app_name = 'forum4'


urlpatterns = [
    path('',views.homePageView, name='home'),
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('users.urls')),
    

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='pass-reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/pass_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/pass_reset_complete.html'),name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path,include, reverse_lazy
from .import views
from django.contrib.auth import views as auth_views
# from .views import activate  


app_name = 'users'

urlpatterns = [

    path('sing-up/', views.register,name='register-url'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('log-in/', views.log,name='log'),
    path('logout/', views.logout_view ,name='logout'),
    path('update-profile/',views.update_profile,name='update_url'),
    path('edit-profile/',views.edit_profile,name='edit_url'),
    path('delete_profile_user/', views.delete_user_profile,name='delete-user'),
    path('password-change/', views.UpdatePassword,name='update_pass'),
    path('confirmation/', views.confirmationView,name='confirmation_page'),
    
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),  

    # path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
    #     views.activate, name='activate'),      
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class User_photo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	user_img = models.ImageField(default='default_user_img/user_img.png',upload_to='user_photos',null=True,blank=True)

	# def save(self):
	# 	super().save(*args, **kwargs) # this will execute and save everything above
	# 	user_img = Image.open(self.image)
	# 	SIZE= , 450
	# 	new_image= img.resize(SIZE, Image.ANTIALIAS)
	# 	new_image.save(self.image.path)

	def __str__(self):
		if self.user:
			return self.user.username
		else:
			return 'unknown'

users/forms.py
from django import forms
from django.forms import Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from .models import User_photo 
from django.forms import ModelForm, TextInput, EmailInput,PasswordInput


from django.contrib.auth.tokens import PasswordResetTokenGenerator  
import six  





class User_photo_form(forms.ModelForm):
	class Meta:
		model = User_photo
		fields = ['user_img']

	def __init__(self, *args, **kwargs):
		super(User_photo_form, self).__init__(*args, **kwargs)

		self.fields['user_img'].widget = forms.FileInput(attrs={'class': 'form-control',})

class Update_user(forms.ModelForm):
	class Meta:
		model = User
		fields = ['email','first_name','last_name']
		
class User_form(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email','password1','password2','first_name','last_name']

	def clean_email(self):
		data = self.cleaned_data['email']
		user_email_count =  User.objects.filter(email=data).count()
		if user_email_count > 0 :
			raise forms.ValidationError("This email is already used")
		return data

	def __init__(self, *args, **kwargs):
		super(User_form, self).__init__(*args, **kwargs)

		self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("please enter your username")})
		self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("please enter your email")})
		self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("please enter your password")})
		self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("please confirm your password")})
		self.fields['first_name'].widget = forms.TextInput(attrs={'class': 'form-control','rows': 1, 'cols': 1,'placeholder': ("please enter your first name* (optional)")})
		self.fields['last_name'].widget = forms.TextInput(attrs={'class': 'form-control','rows': 1, 'cols': 1,'placeholder': ("please enter your last name* (optional)")})


class PasswordForm(PasswordChangeForm):

	def __init__(self, *args, **kwargs):
		super(PasswordForm, self).__init__(*args, **kwargs)

		self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("old password")})
		self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("new password")})
		self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form-control','rows': 1,'required': 'true', 'cols': 1,'placeholder': ("confirm new password")})



# this will create token 
class TokenGen(PasswordResetTokenGenerator):  
	def _make_hash_value(self, user, timestamp):

		return (  
			six.text_type(user.pk) + six.text_type(timestamp) +  
			six.text_type(user.is_active)  
			)  
account_activation_token = TokenGen()  


# 97 oooooooooooooooooooooooooooooooooooooooooo
# 674396531 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
# 674396531 111111111111111111111111111111111111111111
# 97 2222222222222222222222222222222222222222222222222

# The unicode type was renamed to str in Python 3. Use six.text_type to
# make the modified code compatible with Python 2 and Python 3.
# six.text_type = Type for representing (Unicode) textual data. This is unicode() in Python 2 and str in Python 3.

users/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from .forms import User_photo_form, User_form, Update_user ,PasswordForm
from .models import User_photo
from django.contrib.auth import authenticate, login,get_user_model
from django.contrib import messages
from django.contrib.auth import logout
from django.core.files.storage import FileSystemStorage
from django.core.files.uploadedfile import SimpleUploadedFile
from django.utils.encoding import force_bytes, force_str
from django.contrib.sites.shortcuts import get_current_site  
from django.template.loader import render_to_string 
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail import EmailMessage  
from .forms import account_activation_token
import re 



# # uidb64 is user_id encoded in b64
def register(request):
	if request.method == 'POST':
		form = User_form(request.POST)
		user_img_form = User_photo_form(request.POST,request.FILES)
		if form.is_valid() and user_img_form.is_valid() : #and user_img_form.is_valid()
			form.instance.is_active = False
			form.save()
			photo_user = user_img_form.save(commit=False)
			photo_user.user = form.instance 
			photo_user.save()
			#This is  to obtain the current cite domain   
			current_site_info = get_current_site(request)
			mail_subject = 'The Activation link has been sent to your email address'  
			message = render_to_string('users/acc_active_email.html', {  
				# 'form': form,  
				'domain': current_site_info.domain,  
				'uid': urlsafe_base64_encode(force_bytes(form.instance.pk)),
				'token':account_activation_token.make_token(form.instance),  
			})  
			to_email = form.cleaned_data.get('email')  
			email = EmailMessage(  
						mail_subject, message, to=[to_email]  
			)  
			email.send()  
			request.session['form_message'] = "form_message"
			request.session['username'] = form.instance.username
			messages.success(request, 'please go to your email and confirm/click on link to activate account!') 
			return redirect('users:confirmation_page')
		else:
			messages.error(request, 'Something went wrong.')
	else:
		form = User_form()
		user_img_form = User_photo_form()
	return render(request,'users/singup_form.html',{'form':form,'user_img_form':user_img_form})



def activate(request, uidb64, token):  
	User = get_user_model()  
	try:  
		uid = force_str(urlsafe_base64_decode(uidb64))
		# uid = force_text(urlsafe_base64_decode(uidb64))  
		user = User.objects.get(pk=uid)  
	except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
		user = None  
	if user is not None and account_activation_token.check_token(user, token):  
		user.is_active = True  
		user.save()  
		# request.session['form_message'] = "form_message"
		# request.session['username'] = user.username
		messages.success(request, 'hello {} , your account was created successfully, you can login now!'.format(user.username))
		return redirect('home') 
	else:  
		messages.error(request, 'link expired or invalid')
		return redirect('users:confirmation_page')
		# return HttpResponse('Activation link is invalid!')  


def confirmationView(request):  
	return render(request,'users/confirmation.html')



def log(request):
	# this next url will be sent from base.html 
	next_login_url = request.POST.get('next')
	check_url = re.search("password-reset-complete",next_login_url)
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		request.session['seesion_wellcome_login'] = 'session'
		request.session['username'] = username
		if check_url:
			messages.success(request, 'Wellcome {}! Your are logged in!'.format(username))
			return redirect("home")
		messages.success(request, 'Wellcome {}! Your are logged in!'.format(username))
		return redirect(next_login_url)

	else:
		messages.error(request, 'Something went wrong! You are not logged in. Try again!')
		return redirect(next_login_url)



def update_profile(request):
	if 'update_profile_session' in request.session:
		messages.success(request, 'Your profile is updated successfully!')
		del request.session['update_profile_session']
	user = User.objects.get(id=request.user.id)
	update_form2 = User_form(instance=user)
	photo_form =  User_photo_form(instance=user.user_photo)
	return render(request,'users/profile.html',{'user':user,'update_form2':update_form2,'photo_form':photo_form}) 


def edit_profile(request):
	user = User.objects.get(id=request.user.id)
	if request.method == 'POST':
		f = Update_user(request.POST)
		if request.FILES:
			# i am using here name word instead of path coz of s3 bucket
			delete_user_photo = user.user_photo.user_img.name
			fs = FileSystemStorage()
			fs.delete(delete_user_photo)
		updatePhoto = User_photo_form( request.POST,request.FILES,instance=request.user.user_photo)
		if f.is_valid() and updatePhoto.is_valid():
			first = f.cleaned_data['first_name']
			last = f.cleaned_data['last_name']
			email = f.cleaned_data['email']
			img = updatePhoto.cleaned_data['user_img']
		user = User.objects.filter(id=request.user.id).update(last_name=last,first_name=first,email=email)
		updatePhoto.save()
		request.session['update_profile_session'] = 'update_profile_session'
	return redirect('home')
	
def delete_user_profile(request):
	user = User.objects.get(id=request.user.id).delete()
	messages.success(request, 'profile is deleted :( ')
	return redirect('home')
	

def logout_view(request):
	logout(request)
	messages.success(request, 'You are logged out successfully!')
	return redirect('home')


def UpdatePassword(request):
	form = PasswordForm(user=request.user)
	if request.method == 'POST':
		form = PasswordForm(user=request.user, data=request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Hi {}.Your password is updated successfully! You can login now with your new password'.format(request.user.username))
			return redirect('home')
		else:
			messages.error(request, 'Something went wrong. Try again!')

	return render(request,'users/passwordChange.html',{'form':form}) 

users/templates/users/acc_active_email.html
{% autoescape off %}  

<h3>Kindly click below given link to confirm your registration, </h3>
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}  

{% endautoescape %}  

users/templates/users/confirmation.html
{% extends "books/base.html" %}

{% block content %}


<div  style="margin-top: 40px;">

<div style="margin:auto; max-width: 500px;"  class="alert alert-light" role="alert">

{% if messages %}
  <div class="messages" style="width: 100%;">
    {% for message in messages %}
        {% if message.level == 40 %}
      <div class="alert alert-danger" role="alert">
        <h4 style="color: blue; text-align: center;" >{{ message }}</h4>
      </div>
        {% else %}
      <div class="alert alert-success" role="alert">
        <h5 style="color: blue; text-align: center;" >{{ message }}</h5>
      </div>
        {% endif %}
    {% endfor %}
  </div>
{% endif %}
    

  </div>

</div>     


            
{% endblock %}

users/templates/users/login.html
{% extends "books/base.html" %}

{% block content %}

<h1><a href="{% url 'users:logout' %}">Log Out</a></h1>


  <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
          Dropdown
        </button>
      <div class="dropdown-menu">
        <form class="px-4 py-3" method="post" action="{% url 'users:login' %}">
          {% csrf_token %}
          <div class="mb-3">
              <tr> 
                  <td>{{ form.username }}</td>
              </tr>
          </div>
          <div class="mb-3">
              <tr>
                  <td>{{ form.password }}</td>
              </tr>
          </div>
          <div class="mb-3">
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="dropdownCheck">
              <label class="form-check-label" for="dropdownCheck">
                Remember me
              </label>
            </div>
          </div>
          <input type="submit" value="login">
        </form>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">New around here? Sign up</a>
        <a class="dropdown-item" href="#">Forgot password?</a>
  </div>



<h1><a href="{% url 'users:logout' %}">Log Out</a></h1>


{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'users:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>
            
{% endblock %}

users/templates/users/pass_reset_complete.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div  style="margin-top: 40px;">

  <div style="margin:auto; max-width: 500px;"  class="alert alert-success" role="alert">

    <h5>Reset password successfully completed</h5>
    <br>
    <h5>You can login now</h5>


  </div>     

</div>

{% endblock %}

users/templates/users/pass_reset_confirm.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div  style="margin-top: 40px;">

  <div style="margin:auto; max-width: 500px;"  class="alert alert-light" role="alert">



    <h5>Please enter passwords</h5>
    <form method="post">
      {% csrf_token %}
      {{form|crispy}}
      <br>
      <button class="btn btn-primary" type="submit">reset</button>
    </form>

  </div>     

</div>

{% endblock %}

users/templates/users/passwordChange.html
{% extends 'books/base.html' %}
{% load static %}

{% block content %}




<div class="password-change-div-main">


	<div class="password-change-div">
		<h2 style="color:#ff6600; text-align: center;">Hello {{request.user}}</h2>
		<h3 style="color:#009900; text-align: center;">You can change your password here</h3>
		<br>

		{% if messages %}
			{% for message in messages %}
				{% if message.level == 40 %}
					<h4 style="color: red">{{message}}</h4>
				{% endif %}
			{% endfor %}
		{% endif %}

		<form action="{% url 'users:update_pass' %}" method="post">
			{% csrf_token %}

			<h5>please enter your <span style="color:red;">{{form.old_password.label}}</span></h5>
			{{form.old_password.help_text}}
			{{form.old_password}}
		        {% for error in form.old_password.errors %}
		          <h5 style="color: red">{{ error }}</h5>
		        {% endfor %}
			<br>

			<h5>please enter your <span style="color:red;">{{form.new_password1.label}}</span></h5>
			<h5 style="color:blue;">{{form.new_password1.help_text}}</h5>
			{{form.new_password1}}
		        {% for error in form.new_password1.errors %}
		          <h5 style="color: red">{{ error }}</h5>
		        {% endfor %}
			<br>

			<h5><span style="color:red;">{{form.new_password2.label}}</span></h5>
			{{form.new_password2.help_text}}
			{{form.new_password2}}
		        {% for error in form.new_password2.errors %}
		          <h5 style="color: red">{{ error }}</h5>
		        {% endfor %}
			<br>


			<button class="btn btn-primary" type="submit">Update</button>
		</form>

	</div>
</div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div  style="margin-top: 40px;">

  <div style="margin:auto; max-width: 500px;"  class="alert alert-light" role="alert">



    <h5>to reset your password enter email</h5>
    <h5>your username will be available in email</h5>
    <form method="post">
      {% csrf_token %}
      {{form|crispy}}
      <br>
      <button class="btn btn-primary" type="submit">send</button>
    </form>

  </div>     

</div>
  


{% endblock %}

users/templates/users/password_reset_done.html
{% extends "books/base.html" %}

{% block content %}


<div  style="margin-top: 40px;">

  <div style="margin:auto; max-width: 500px;"  class="alert alert-light" role="alert">

  <h5>Password reset sent<br><br>
  We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br><br>

  If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
  </h5>
    

  </div>

</div>     


            
{% endblock %}

users/templates/users/profile.html
{% extends 'books/base.html' %}
{% load static %}


{% block content %}


<div class="profile-main-div">
	{% if messages %}
		<div class="messages">
		    {% for message in messages %}
	        	{% if message.level == 40 %}
					<div class="alert alert-danger" role="alert">
					  <h4 style="color: blue; margin: auto;" >{{ message }}</h4>
					</div>
	        	{% else %}
					<div class="alert alert-success" role="alert">
					  <h5 style="color: blue; margin: auto;" >{{ message }}</h5>
					</div>
	       		{% endif %}
		    {% endfor %}
	    </div>
	{% endif %}
	<br>
	<h4 style="text-align: center; color: green;">Hello {{user.username}}</h4>
	<br>

	<img src="{{user.user_photo.user_img.url}}" alt="photo" class="img-thumbnail" width="200">
	<br>


	<form action="{% url 'users:edit_url' %}" method="post" enctype="multipart/form-data" style="width: 100%; ">
		{% csrf_token %}
		<div>
			<h4>Update your first name</h4>
			{{update_form2.first_name}}
		</div>
		<hr>
		<div>
			<h4>Update your last name</h4>
			{{update_form2.last_name}}
		</div>
		<hr>
		<div>
			<h4>Update your email name</h4>
			{{update_form2.email}}
		</div>
		<hr>
		<div>
			<h4>Update your photo</h4>
			{{photo_form.user_img}}
		</div>
		<br>
		<div class="d-grid gap-2">
			<button class="btn btn btn-success btn-lg" type="submit">Update</button>
		</div>
	</form>
	<br>

	<form action="{% url 'users:delete-user' %}" method="post" style="width: 100%; ">
			{% csrf_token %}
			<div class="d-grid gap-2">
				<button class="btn btn btn-danger btn-lg" type="submit">delete-profile</button>
			</div>
		</form>
</div>
{% endblock %}

users/templates/users/singup_form.html
{% extends 'books/base.html' %}
{% load static %}

{% block content %}



<div class="singup-title"><h3>Wellcome Sing Up Here</h3></div>
<div class="main-singup-div">
<br>
  <form method="post" enctype="multipart/form-data">
  	<div class="singup-div">

		{% if messages %}
    		{% for message in messages %}
    			<h4 style="color: red">{{message}}</h4>
    		{% endfor %}
		{% endif %}

	    {% csrf_token %}
	    {% for field in form %}
	    	<h5 style="color: #cc6600">{{ field.label }}</h5>
	    	{{field}}
	    	{{field.help_text}}
	        {% for error in field.errors %}
	          <h5 style="color: red">{{ error }}</h5>
	        {% endfor %}
	    	<hr>
	    {% endfor %}

	    {% for img_field in user_img_form %}
	    	<h5 style="color: #cc6600">{{ img_field.label }}</h5>
	    	{{img_field }}
	        {% for error in img_field.errors %}
	          <h6 style="color: red">{{ error }}</h6>
	        {% endfor %}
	    {% endfor %}

	    <br>
	    <br>
		<div class="d-grid gap-2">
		  <button class="btn btn-primary" type="submit">Sing Up</button>
		</div>
	</div>
  </form>
 </div>



{% endblock %}