books/urls.py
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'books'

urlpatterns = [


	path('books-by-genres/',views.return_books_by_ganres,name='books_by_ganres'),
	path('comment-rating-system/',views.comment_like_dislike_system,name='comment_system'),
	path('book-rating-system/',views.book_like_dislike_system,name='system'),
	path('books-you-have-searched-for/',views.search_book,name='search'),
	path('delete-comment/<int:comm_id>/<int:book_id>/',views.delete_comment,name='comm_delete'),
	path('star/<int:book_id>/',views.rating_star_system,name='rating_star'),
	path('un-rate/<str:slug>/<int:user_id>/',views.delete_user_stars,name='user_stars_delete'),
	path('book-by-genre/<str:gen>/',views.get_one_genre_books ,name='one_genre'),

	path('page-num-update-comm/<slug:slug>/<page_num_update_comment>/',views.book, name='book-comment'),
	path('book/<slug:slug>/',views.book, name='book'),

]

forum4/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .import views



app_name = 'forum4'


urlpatterns = [
    path('',views.homePageView, name='home'),
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('users.urls')),
    

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='pass-reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/pass_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/pass_reset_complete.html'),name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse



class Genres(models.Model):
	genre = models.CharField(max_length=30)

	def __str__(self):
		return self.genre


class Book(models.Model):

	title = models.CharField(max_length=200)
	writter = models.CharField(max_length=200)
	published = models.CharField(max_length=20)
	pages = models.PositiveSmallIntegerField()
	file = models.FileField(upload_to='book_files',null=True,blank=True)
	info = models.TextField()
	date_posted = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(upload_to='books_photos',null=True,blank=True)
	slug = models.SlugField(max_length=200,null=True,blank=True)
	genres = models.ManyToManyField(Genres)
	likes = models.ManyToManyField(User,related_name='likes',blank=True)
	dislikes = models.ManyToManyField(User,related_name='dislikes',blank=True)


	def __str__(self):
		return self.title

	# slugify title and add num at the end of slug, every time new book is made, it counts all book's objects and then add finnaly number to slug
	def slugify_title(self):
		count = Book.objects.all().count()
		self.slug = slugify(self.title) + '-' + str(count)

	# resize image and save 
	def save(self):
		self.slugify_title()
		super().save() # this will execute and save everything above
		# img = Image.open(self.image)
		# SIZE= 298, 450
		# # SIZE= 200, 200
		# new_image= img.resize(SIZE, Image.ANTIALIAS)
		# new_image.save(self.image.path)

	# 
	@property
	def likes_dislikes_procentage(self):
		total_likes_dislikes = self.likes.count() + self.dislikes.count()
		if total_likes_dislikes == 0:
			total_likes_procentage = 0
			total_dislikes_procentage = 0
		else:
			total_likes_procentage = (self.likes.count() / total_likes_dislikes) * 100
			total_dislikes_procentage = (self.dislikes.count() / total_likes_dislikes) * 100
		return round(total_likes_procentage), round(total_dislikes_procentage)

	# @property
	def files(self):
		if self.file:
			return self.file.url
		else:
			return 'no file'


	def get_absolute_url(self):		
		return reverse('books:book', kwargs={'slug' : self.slug})


class Rating_star_system(models.Model):
	star = models.OneToOneField(Book,on_delete=models.CASCADE,null=True,blank=True)
	star_1 = models.ManyToManyField(User,blank=True,related_name='star_1')
	star_2 = models.ManyToManyField(User,blank=True,related_name='star_2')
	star_3 = models.ManyToManyField(User,blank=True,related_name='star_3')
	star_4 = models.ManyToManyField(User,blank=True,related_name='star_4')
	star_5 = models.ManyToManyField(User,blank=True,related_name='star_5')

	def __str__(self):
		return self.star.title

	@property
	def total(self):
		add_all_users = self.star_1.count() + self.star_2.count() + self.star_3.count() + self.star_4.count() +self.star_5.count()
		multiplie_users = self.star_5.count() * 5 + self.star_4.count() * 4 + self.star_3.count() * 3 + self.star_2.count() * 2 + self.star_1.count() * 1

		if multiplie_users > 0 and add_all_users > 0:
			total_rating = multiplie_users/add_all_users
		else:
			total_rating = 0

		return round(total_rating,1) , add_all_users

	@property
	def each_star_procentage(self):
		add_all_users = self.star_1.count() + self.star_2.count() + self.star_3.count() + self.star_4.count() +self.star_5.count()

		if add_all_users != 0:
			star_1 = (self.star_1.count() / add_all_users) * 100
			star_2 = (self.star_2.count() / add_all_users) * 100	
			star_3 = (self.star_3.count() / add_all_users) * 100	
			star_4 = (self.star_4.count() / add_all_users) * 100	
			star_5 = (self.star_5.count() / add_all_users) * 100
			return round(star_1),round(star_2),round(int(star_3)), round(star_4), round(star_5),'{}%'.format(round(int(star_1))),'{}%'.format(round(int(star_2))),'{}%'.format(round(int(star_3))),'{}%'.format(round(int(star_4))),'{}%'.format(round(int(star_5)))
		else:
			pass



class Users_stars(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
	stars = models.SmallIntegerField(null=True,blank=True)
	book = models.ForeignKey(Book,on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		if not self.user:
			return "{} //// user: ".format(self.book.title)
		return "BOOK: {}-------------USER: {}-------------STARS-GIVEN: {}".format(self.book.title,self.user.username,self.stars)



class Comments(models.Model):
	comment = models.TextField(max_length=30000,null=True,blank=True)
	book = models.ForeignKey(Book, on_delete=models.CASCADE,null=True,blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
	comment_likes = models.ManyToManyField(User,related_name='comment_likes',blank=True)
	comment_dislikes = models.ManyToManyField(User,related_name='comment_dislikes',blank=True)
	date_comment_modified = models.DateField(auto_now_add=True,null=True, blank=True) # objects firts time created
	date_comment_posted = models.DateField(auto_now=True,null=True, blank=True) # every time comm is modified i will save the time
	user_book_star = models.OneToOneField(Users_stars, on_delete=models.CASCADE,null=True,blank=True)

	def __str__(self):
		if not self.user:
			return 'BOOK: {}------------ USER: {} '.format(self.book.title,'anonimus-user')
		return 'BOOK: {}------------ USER: {} '.format(self.book.title,self.user.username)

templates/homePage.html
{% extends 'books/base.html' %}
{% load static %}

{% block content %}


{% if messages %}
  <div class="messages">
    {% for message in messages %}
        {% if message.level == 40 %}
      <div class="alert alert-danger" role="alert">
        <h4 style="color: blue; margin: auto;" >{{ message }}</h4>
      </div>
        {% else %}
      <div class="alert alert-success" role="alert">
        <h5 style="color: blue; margin: auto;" >{{ message }}</h5>
      </div>
        {% endif %}
    {% endfor %}
  </div>
{% endif %}


<div class="accordion accordion-flush info" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
       <h5>Info about site <span style="color: green;">(read me - 30sec read)</span> </h5>
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body"><h5 class="">Hello everyone. Wellcome to my website. Here you can find the books you would like to read in PDF format. The books can be downloaded by all public for free no registration needed. You can also register and use the options like commeting, rating,reviewing etc.
    Thank you all, I wish you good day. 
    </h5> </div>
    </div>
  </div>
</div>




<div class="download-title"> 
  <h1 class="display-6">Most Read Books</h1>
</div>

<div class="main-download">
  <div class="download-books">
    {% for books in book %}
      <span class="d-inline-block" tabindex="0" data-bs-html="true" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="

      <div class='data-title-writer'>
        <div class='data-title'><h5>{{books.title}}</h5></div>
        <div class='data-writter'><h6>{{books.writter}} </h6></div>
      </div>

      <div class='data-main-div'>
        <div class='data-stars-rate-num'>
          <div class='z'>
          {% if books.rating_star_system.total.0 == 0 %}
            <img src='{% static 'star/0-stars-big.png'%}' class='star-vertical-aling' alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 1  or books.rating_star_system.total.0 < 1.3 %}
            <img src='{% static 'star/1-star-big.png' %}'class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 1.3 or books.rating_star_system.total.0 < 1.8 %}
            <img src='{% static 'star/1.5-stars-small.png' %}'class='star-vertical-aling'alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 1.8 or books.rating_star_system.total.0 < 2.3 %}
            <img src='{% static 'star/2-stars-small.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 2.3 or books.rating_star_system.total.0 < 2.8 %}
            <img src='{% static 'star/2.5-stars-big.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 2.8 or books.rating_star_system.total.0 < 3.3 %}
            <img src='{% static 'star/3-stars-big.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 3.3 or books.rating_star_system.total.0 < 3.8 %}
            <img src='{% static 'star/3.5-stars-big.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 3.8 or books.rating_star_system.total.0 < 4.3 %}
            <img src='{% static 'star/4-stars-small.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 == 4.3 or books.rating_star_system.total.0 < 4.8 %}
            <img src='{% static 'star/4.5-stars-small.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% elif books.rating_star_system.total.0 > 4.7  %}
            <img src='{% static 'star/5-stars-big.png' %}' class='star-vertical-aling'  alt='My image' width='100'>
          {% endif %}
          </div>&nbsp;
          <div><h6>{{books.rating_star_system.total.0}}</h6></div>
        </div>
          <div class='all-genres'>
            <div class='all-genres-inside' >
              {% for gen in books.genres.all %}
                <p class='font-monospace'>{{gen}}</p>&nbsp;&nbsp;
              {% endfor %}
            </div>
          </div>

          <div>{{books.comments_set.all.count}} comments</div>

      </div>
      <h6 class='data-book-info'>{{books.info }}</h6>
      ">    
      <a href="{% url 'books:book' slug=books.slug %}"><img src="{{books.image.url}}" class="img-thumbnail img-front-page" width=""></a></span>
    {% endfor %}
  </div>

  <div class="download-books-screen-417px">
    {% for books in book %}  
      <a href="{% url 'books:book' slug=books.slug %}"><img src="{{books.image.url}}" class="img-thumbnail img-front-page" width=""></a></span>  
    {% endfor %}
  </div>


  <div class="genres" >
    <form method="post" action="{% url 'books:books_by_ganres' %}"> 
      {% for gen in gen %}
        <div class="form-check content-genres">
          <input class="form-check-input" type="checkbox" name="value" value="{{ gen }}" id="flexCheckDefault">
          <label class="form-check-label " for="flexCheckDefault">
            <h5 class="">{{gen}}</h5>
          </label>
        </div>
      {% endfor %}
      {% csrf_token %}
          <button class="btn btn btn-success btn-sm" type="submit">Search books by genre</button>
    </form>
  </div>

  <br>
  <div class="genres-column" >
    <form method="post" action="{% url 'books:books_by_ganres' %}"> 
      {% for gen in gen %}
        <div class="form-check-inline">
          <input class="form-check-input" type="checkbox" name="value" value="{{ gen }}" id="flexCheckDefault">
            <label class="form-check-label " for="flexCheckDefault">
            <h5 class="">{{gen}}</h5>

        </div>
      {% endfor %}
      {% csrf_token %}
        <br>
          <button class="btn btn btn-success btn-sm" type="submit">Search books by genre</button>
    </form>
  </div>
</div>


{% endblock %}