books/urls.py
from django.urls import path,include
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'books'

urlpatterns = [


	path('books-by-genres/',views.return_books_by_ganres,name='books_by_ganres'),
	path('comment-rating-system/',views.comment_like_dislike_system,name='comment_system'),
	path('book-rating-system/',views.book_like_dislike_system,name='system'),
	path('books-you-have-searched-for/',views.search_book,name='search'),
	path('delete-comment/<int:comm_id>/<int:book_id>/',views.delete_comment,name='comm_delete'),
	path('star/<int:book_id>/',views.rating_star_system,name='rating_star'),
	path('un-rate/<str:slug>/<int:user_id>/',views.delete_user_stars,name='user_stars_delete'),
	path('book-by-genre/<str:gen>/',views.get_one_genre_books ,name='one_genre'),

	path('page-num-update-comm/<slug:slug>/<page_num_update_comment>/',views.book, name='book-comment'),
	path('book/<slug:slug>/',views.book, name='book'),

]

forum4/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .import views



app_name = 'forum4'


urlpatterns = [
    path('',views.homePageView, name='home'),
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('users.urls')),
    

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='pass-reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/pass_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/pass_reset_complete.html'),name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path,include, reverse_lazy
from .import views
from django.contrib.auth import views as auth_views
# from .views import activate  


app_name = 'users'

urlpatterns = [

    path('sing-up/', views.register,name='register-url'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('log-in/', views.log,name='log'),
    path('logout/', views.logout_view ,name='logout'),
    path('update-profile/',views.update_profile,name='update_url'),
    path('edit-profile/',views.edit_profile,name='edit_url'),
    path('delete_profile_user/', views.delete_user_profile,name='delete-user'),
    path('password-change/', views.UpdatePassword,name='update_pass'),
    path('confirmation/', views.confirmationView,name='confirmation_page'),
    
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),  

    # path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
    #     views.activate, name='activate'),      
]

books/forms.py
from django import forms
from django.forms import Form
from django.contrib.auth.models import User
from .models import Comments,Book   #, Replys
from django.forms import ModelForm, TextInput, EmailInput,PasswordInput
# from crispy_forms.helper import FormHelper



class Comment_form(forms.ModelForm):
	class Meta:
		model = Comments
		fields = ['comment']
		
	def __init__(self, *args, **kwargs):
		super(Comment_form, self).__init__(*args, **kwargs)

		self.fields['comment'].widget = forms.Textarea(attrs={'class': 'form-control', 'background-color':'ffcccc', 'rows': 5,'required': 'true', 'cols': 20,'placeholder': ("What do you think about this book?")})
		self.fields['comment'].label = False
		self.fields['comment'].strip = False


class Comment_form_disabled(forms.Form):

	disabled_field = forms.CharField(label=False,strip = False,widget=forms.Textarea(attrs={'class': 'form-control', 'background-color':'ffcccc', 'disabled':'true', 'rows': 5, 'cols': 20,'placeholder': ("please login/register to be able to comment")}))






class Rating_form(forms.ModelForm):
	class Meta:
		model = Book
		fields = ['likes','dislikes']

books/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect
from django.urls import reverse
from .models import Book, Genres,Comments,Rating_star_system,Users_stars
from .forms import Rating_form,Comment_form , Comment_form_disabled
from django.db.models import Count
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.models import AnonymousUser
from django.core.paginator import Paginator





def return_books_by_ganres(request):
	values_list = request.POST.getlist('value') # get list of all genres that client choos
	value_string = ' , '.join(values_list)
	book = Book.objects.filter(genres__genre__in=values_list).distinct() # ['History','Adventure']
	return render(request,'books/books_by_genres.html',{'book':book,'value_string':value_string})


def get_one_genre_books(request,gen):
	book = Book.objects.filter(genres__genre=gen)
	return render(request,'books/book_by_one_genre.html',{'book':book,'gen':gen})




def book(request,slug,page_num_update_comment=1):
	if ( 'session' in request.session):
		username = request.session['username']
		messages.success(request, 'Wellcome {}! Your are logged in!'.format(username))
	book = Book.objects.get(slug=slug)
	rating_star_system = Rating_star_system.objects.get(star=book.id) 
	list_book_genres = book.genres.values_list('genre', flat=True) 
	return_books_by_ganres = Book.objects.filter(genres__genre__in=list_book_genres).annotate(num_authors=Count('likes')).order_by('-num_authors')
	comment = Comments.objects.filter(book=book).annotate(num_authors=Count('comment_likes')).order_by('-num_authors')
	page_num = request.GET.get('page_num')
	if page_num == None:
		page_num = page_num_update_comment

	comments = Paginator(comment, 5, orphans=4)
	page = comments.page(page_num)
	user_stars_per_book_on_coment = Users_stars.objects.filter(book=book)
	try:
		user_star_book = Users_stars.objects.get(Q(book=book) & Q(user_id=request.user.id))
	except ObjectDoesNotExist:
		user_star_book = None
	viewed_recently = None
	if 'viewed_recently' in request.session:
		if book.id in request.session['viewed_recently']:
			request.session['viewed_recently'].remove(book.id)
		request.session['viewed_recently'].insert(0, book.id)
		if len(request.session['viewed_recently']) > 3:
			request.session['viewed_recently'].pop()
	else:
		# this will return list called viewed_recently
		request.session['viewed_recently'] = [book.id]
	request.session.modified = True
	recently_viewed_books = Book.objects.filter(id__in=request.session['viewed_recently'])
	update_form = None
	comm_idx = request.GET.get('comm_idx')
	if comm_idx:
		# content of the comment
		comm = Comments.objects.get(Q(book=book) & Q(id=comm_idx)).comment
		comm2 = Comments.objects.get(Q(book=book) & Q(id=comm_idx)).id
		form = Comment_form()
		update_form = Comment_form(initial={'comment': comm,'comm_id':comm2})
	if request.method =='POST':
		comm_id = request.POST.get('comm_id')
		if comm_id:
			comm = Comments.objects.get(Q(book=book) & Q(id=comm_id) & Q(user=request.user))
			comm.comment = request.POST['comment']
			comm.save()
			messages.success(request, 'Your comment was updated successfully')
			return HttpResponseRedirect(reverse('books:book-comment', args=(book.slug,page_num,)))

		form = Comment_form(request.POST)
		if form.is_valid():
			form_save = form.save(commit=False)
			form_save.user = request.user
			form_save.book = book
			form.save()
			return HttpResponseRedirect(reverse('books:book', args=(book.slug,)))

	else:
		form = Comment_form()
		form_2 = Comment_form_disabled()
	return render(request,'books/book_page.html',
		{
		'book':book,
		'form':form,
		'return_books_by_ganres':return_books_by_ganres,
		'rating_star_system':rating_star_system,
		'user_star_book':user_star_book,
		'user_stars_per_book_on_coment':user_stars_per_book_on_coment,
		'recently_viewed_books':recently_viewed_books,
		'page':page,
		'comments':comments,
		'comment':comment,
		'update_form':update_form,
		'form_2': form_2
		})

def book_like_dislike_system(request):
	dislike = request.POST.get('dislike')
	like = request.POST.get('like')
	user = request.POST.get('user')
	slug = request.POST.get('slug')
	book = Book.objects.get(slug=slug)

	if like and  book.likes.filter(id=user).exists():
		book.likes.remove(request.user)
	elif like and not book.likes.filter(id=user).exists():
		book.likes.add(user)
		if book.dislikes.filter(id=user).exists():
			book.dislikes.remove(request.user)
	elif dislike and book.dislikes.filter(id=user).exists():
		book.dislikes.remove(request.user)
	elif dislike and not book.dislikes.filter(id=user).exists():
		book.dislikes.add(user)
		if book.likes.filter(id=user).exists():
			book.likes.remove(request.user)
	return HttpResponseRedirect(reverse('books:book', args=(book.slug,)))


# same system as above
def comment_like_dislike_system(request):
	dislike = request.POST.get('dislike')
	like = request.POST.get('like')
	user = request.POST.get('user')
	slug = request.POST.get('slug')
	comment_id = request.POST.get('comment_id')
	comment = Comments.objects.get(id=comment_id)

	if like and  comment.comment_likes.filter(id=user).exists():
		comment.comment_likes.remove(request.user)
	elif like and not comment.comment_likes.filter(id=user).exists():
		comment.comment_likes.add(user)
		if comment.comment_dislikes.filter(id=user).exists():
			comment.comment_dislikes.remove(request.user)
	elif dislike and comment.comment_dislikes.filter(id=user).exists():
		comment.comment_dislikes.remove(request.user)
	elif dislike and not comment.comment_dislikes.filter(id=user).exists():
		comment.comment_dislikes.add(user)
		if comment.comment_likes.filter(id=user).exists():
			comment.comment_likes.remove(request.user)
	return HttpResponseRedirect(reverse('books:book', args=(slug,)))


# here you are reciving values from rate_it_stars.html (book_id and num that represents value)#
def rating_star_system(request,book_id):
	stars = request.POST.get('num')
	stars = int(stars)
	book = Book.objects.get(id=book_id)
	star_sytem = Rating_star_system.objects.get(star=book_id)

	if stars == 1 and not star_sytem.star_1.filter(id=request.user.id).exists():
		star_sytem.star_1.add(request.user)
		if star_sytem.star_2.filter(id=request.user.id).exists():
			star_sytem.star_2.remove(request.user)
		elif star_sytem.star_3.filter(id=request.user.id).exists():
			star_sytem.star_3.remove(request.user)
		elif star_sytem.star_4.filter(id=request.user.id).exists():
			star_sytem.star_4.remove(request.user)
		elif star_sytem.star_5.filter(id=request.user.id).exists():
			star_sytem.star_5.remove(request.user)

	elif stars == 2 and not star_sytem.star_2.filter(id=request.user.id).exists():
		star_sytem.star_2.add(request.user)
		if star_sytem.star_1.filter(id=request.user.id).exists():
			star_sytem.star_1.remove(request.user)
		elif star_sytem.star_3.filter(id=request.user.id).exists():
			star_sytem.star_3.remove(request.user)
		elif star_sytem.star_4.filter(id=request.user.id).exists():
			star_sytem.star_4.remove(request.user)
		elif star_sytem.star_5.filter(id=request.user.id).exists():
			star_sytem.star_5.remove(request.user)

	elif stars == 3 and not star_sytem.star_3.filter(id=request.user.id).exists():
		star_sytem.star_3.add(request.user)
		if star_sytem.star_1.filter(id=request.user.id).exists():
			star_sytem.star_1.remove(request.user)
		elif star_sytem.star_2.filter(id=request.user.id).exists():
			star_sytem.star_2.remove(request.user)
		elif star_sytem.star_4.filter(id=request.user.id).exists():
			star_sytem.star_4.remove(request.user)
		elif star_sytem.star_5.filter(id=request.user.id).exists():
			star_sytem.star_5.remove(request.user)


	elif stars == 4 and not star_sytem.star_4.filter(id=request.user.id).exists():
		star_sytem.star_4.add(request.user)
		if star_sytem.star_1.filter(id=request.user.id).exists():
			star_sytem.star_1.remove(request.user)
		elif star_sytem.star_2.filter(id=request.user.id).exists():
			star_sytem.star_2.remove(request.user)
		elif star_sytem.star_3.filter(id=request.user.id).exists():
			star_sytem.star_3.remove(request.user)
		elif star_sytem.star_5.filter(id=request.user.id).exists():
			star_sytem.star_5.remove(request.user)

	elif stars == 5 and not star_sytem.star_5.filter(id=request.user.id).exists():
		star_sytem.star_5.add(request.user)
		if star_sytem.star_1.filter(id=request.user.id).exists():
			star_sytem.star_1.remove(request.user)
		elif star_sytem.star_2.filter(id=request.user.id).exists():
			star_sytem.star_2.remove(request.user)
		elif star_sytem.star_3.filter(id=request.user.id).exists():
			star_sytem.star_3.remove(request.user)
		elif star_sytem.star_4.filter(id=request.user.id).exists():
			star_sytem.star_4.remove(request.user)
	messages.success(request, 'You rated this book with {} stars'.format(stars))
	return HttpResponseRedirect(reverse('books:book', args=(book.slug,)))


def search_book(request):
	value = request.POST.get('value')
	value = value.split()  # ['aa', 'bb', 'cc']
	num = 0
	while len(value) <= 8:
		add_value = value[num]
		value.append(add_value)
		num = num + 1 


	queryset = Book.objects.filter(
    	Q(title__icontains=value[0]) &
    	Q(title__icontains=value[1]) &
    	Q(title__icontains=value[2]) &
    	Q(title__icontains=value[3]) &
    	Q(title__icontains=value[4]) &
    	Q(title__icontains=value[5]) &
    	Q(title__icontains=value[6]) &
    	Q(title__icontains=value[7]) 
	)

	return render(request,'books/searched_books.html',{'queryset':queryset})



def delete_comment(request,comm_id,book_id):
	messages.success(request, 'Your comment was deleted successfully')
	book = Book.objects.get(id=book_id)
	comment = Comments.objects.filter(book=book,id=comm_id).delete()
	return HttpResponseRedirect(reverse('books:book', args=(book.slug,)))


def delete_user_stars(request,user_id,slug):
	messages.success(request, 'You unrated this book successfully')

books/templates/books/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="{% static 'books_css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'books_css/info.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'books_css/book.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'books_css/searched_books_css.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'userapp_css/register_css.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'userapp_css/login_css.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'userapp_css/profile_css.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'userapp_css/changePassword.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar-main w-100 sticky-top">
  <nav class="navbar ">
    <div class="nav-bar">
       <!--LOGIN SYSTEM  -->
      {% if user.is_authenticated %}
        <div class="dropdown ">
          <button class="btn btn-dark dropdown-toggle " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Hello {{user}}
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="{% url 'users:update_url' %}">Update profile</a></li>
            <li><a class="dropdown-item" href="{% url 'users:update_pass' %}">Change Password</a></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
          </ul>
        </div>
      {% else %}
        <div class="dropdown login">
            <button class="btn btn-secondary dropdown-toggle btn-info" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
              Login
            </button>
          <div class="dropdown-menu">
              <form class="px-4 py-3" method="post" action="{% url 'users:log' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" name="username"  class="form-control" placeholder="username">
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="password">
                </div>
                <div class="mb-3">
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="dropdownCheck">
                    <label class="form-check-label" for="dropdownCheck">
                      Remember me
                    </label>
                  </div>
                </div>
                <button type="submit" name="next" value="{{request.path}}" class="btn btn-info">Login</button>
              </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'users:register-url' %}">New around here? Sign up</a>
            <a class="dropdown-item" href="{% url 'pass-reset' %}">Forgot password or username?</a>
          </div>
        </div>
      {% endif %}
      <div class="base-search-form w-100">
         <form class="d-flex w-100" action="{% url 'books:search' %}"  method="post">
            {% csrf_token %}
            <input class="form-control me-1" type="text" placeholder="Search Books" aria-label="Search"  name="value" value="" required>
            <input class="btn btn-success" type="submit" id="button-addon2"></input>
        </form> 
      </div>
      <a href="{% url 'home' %}"><img src="{% static 'icons/logo-small.png' %}"  alt="My image"></a>
    </div>
  </nav>
</div>

<div class="base-search-form-2">
  <form class="d-flex w-100" action="{% url 'books:search' %}"  method="post">
    {% csrf_token %}
    <input class="form-control me-1" type="text" placeholder="Search Books" aria-label="Search"  name="value" value="" required>
    <input class="btn btn-success" type="submit" id="button-addon2"></input>
  </form> 
</div>


	{% block content %}
	{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
</script>

<script type="text/javascript">
  var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
  var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl)
  })
</script>


<script>
function myFunction() {
  document.getElementById("demo").style.display = 'inline';
}
</script>

<script type="text/javascript">
  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl)
})

</script>

</body>
</html>

books/templates/books/carousel.html
<div id="carouselExampleInterval" class="carousel slide book-you-might-like" data-bs-ride="carousel">
  <h5>might like</h5>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="1">
      <img class='img-thumbnail image-in-carousel' src="{{book.image.url}}" class="d-block "  >
    </div>
    {% for books in return_books_by_ganres %}
      {% if not books.slug == book.slug %}
        <div class="carousel-item" data-bs-interval="3500">
          <a href="{% url 'books:book' slug=books.slug %}"><img class='img-thumbnail image-in-carousel d-block w-100' src="{{books.image.url}}"></a>
        </div>
      {% endif %}
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

books/templates/books/edit.html
<form action="{{book.get_absolute_url}}#comm-{{comment.id}}" method="get" class="form">
  <input type="hidden" name="comm_idx" value="{{comment.id}}">
  <input type="hidden" name="page_num" value="{{page.number}}">
  <button type="submit"  class="btn btn-outline-warning btn-sm">Edit</button>
</form>

books/templates/books/rate_it_stars.html
{% load static %}
<img src="">

<!-- here are 5 icons of stars, each star icon has a value ,that is sent to url then to rating_star_system.views -->
<!-- this form is cheking if user is logged in and if user had rated the book -->
{% if user.is_authenticated and user_star_book.stars > 0 %}
<form method="post" action="{% url 'books:rating_star' book_id=book.id %}" >
	<div class="btn-group me-2 button-stars lll" role="group" aria-label="First group">
		{% csrf_token %}
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="1" data-bs-toggle="tooltip" data-bs-placement="bottom" title="1 star"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="2 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="3" data-bs-toggle="tooltip" data-bs-placement="bottom" title="3 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="4" data-bs-toggle="tooltip" data-bs-placement="bottom" title="4 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="5" data-bs-toggle="tooltip" data-bs-placement="bottom" title="5 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	</div>
	<h6 style="text-align: center; margin-top: 10px;">You rated it {{user_star_book.stars}}  <i class="bi bi-star-fill"></i></h6>	
</form>

<!-- this form its just un-rate button, to delete your rate   -->
<form method="post" action="{% url 'books:user_stars_delete' slug=book.slug user_id=request.user.id %}">
	{% csrf_token %}

	<div class="d-grid gap-2 ">
	  <button class="btn btn-outline-danger btn-sm" type="submit"><h6>un-rate</h6></button>
	</div>

</form>



<!-- this form is checking  if user is looged but did not rate it -->
{% elif user.is_authenticated %}
<form method="post" action="{% url 'books:rating_star' book_id=book.id %}" >
	<div class="btn-group me-2 button-stars lll" role="group" aria-label="First group">
		{% csrf_token %}
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="1" data-bs-toggle="tooltip" data-bs-placement="bottom" title="1 star"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="2 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="3" data-bs-toggle="tooltip" data-bs-placement="bottom" title="3 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="4" data-bs-toggle="tooltip" data-bs-placement="bottom" title="4 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="5" data-bs-toggle="tooltip" data-bs-placement="bottom" title="5 stars"><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	</div>
	<h6 style="text-align: center;">Rate it!</h6>
	
</form>


<!-- this form to see if user is not logged in -->
{% else %}
<div data-bs-toggle="tooltip" data-bs-placement="bottom" title="Please login or register">
	<h6 style="text-align: center;">To rate a book please login!</h6>
	<div class="btn-group me-2 button-stars lll" role="group" aria-label="First group">
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="1"  disabled><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="2"  disabled><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="3" disabled><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="4" disabled><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	    <button type="submit" class="btn btn-outline-warning btn-sm" name="num" value="5" disabled><img src="{% static 'icons/index.png' %}" class="star"  alt="My image" width="17"></button>
	</div>
</div>


{% endif %}

books/templates/books/show-All-Books-Genres-And-Star-Rating-System-417px-screen.html
<div class="star-rating-system-screen-417px">
  <!-- rating_star_system.total.1 = return total num of all users -->
  <div class="star-rating-system-inside-417" style="color: green; margin: 5px;"><p>{{rating_star_system.total.1}}-ratings</p></div>
  <div class="star-rating-system-inside-417" style="color: green; margin: 5px;"><p>{{comment.count}}-comments</p></div> 
</div>
<!-- screen-417px -->
<div class="all-genres-2">
  <div class="all-genres-inside" >
    {% for gen in book.genres.all %}
      <a href="{% url  'books:one_genre' gen=gen.genre %}"><p class="font-monospace">{{gen.genre}}</p></a>&nbsp;&nbsp;
    {% endfor %}
  </div>
</div>